### ISSUE TITLE
Wesite is unavailable ! ---> http://sdn-wise.dieei.unict.it 

### ISSUE THREAD

**Issue by Oharaddzi** [sdnwiselab/sdn-wise-contiki#10]
Hi all!

Have you noticed that the official SDN-Wise website became unavailable ? [http://sdn-wise.dieei.unict.it]
Anyone knows why ?

It would be quite importan for me to reach the site again as I am working on a school project with SDN-Wise and would like to follow the instructions of the Get Started tutorial and the Controlling Heterogenous one as well.

Is there anyone out there who still has the instruction or command set or even maybe a downloaded version of the tutorials ?

Thank you

**Comment by basmahassan123** [comment]
Me too, i want it indeed

**Comment by SebMilardo** [comment]
Hi guys,

The whole website (and all our backups) were hosted on some servers at the University of Catania. Unfortunately, most of the servers are actually under maintenance and we do not know when everything will be restored. I'll keep you updated.

**Comment by georgefatsis** [comment]
Hi Milardo, 

Could you provide us the instructions to start sdn wise and onos sdn wise. I mean the steps after the installation.

Kind Regards,
GF

**Comment by ANJUKOTTAKKAL** [comment]
I am studying security issues in SDWSN.
(http://sdn-wise.dieei.unict.it/docs/guides/GetStartedONOS.html) is not working current days.
so i need some basic information about SDWSN framework implementation
please can you help me.

**Comment by basmahassan123** [comment]
Please, sir provide us with the link at the university or upload the complete tutorial, because we want keep our study working

**Comment by SebMilardo** [comment]
Probably the website will come back online in January 

While waiting, you might want to give a shot to cached content that you can find around the web. For instance, archive.org could be an option. Here are some links:

- Get Started with SDN-WISE
http://web.archive.org/web/20180410161246/http://sdn-wise.dieei.unict.it/docs/guides/GetStarted.html

- Understanding the SDN-WISE Core
http://web.archive.org/web/20170706151953/http://sdn-wise.dieei.unict.it:80/docs/guides/Core.html

- Controlling heterogeneous networks using SDN-WISE and ONOS
http://web.archive.org/web/20180424031035/http://sdn-wise.dieei.unict.it/docs/guides/GetStartedONOS.html

Hope this helps.

**Comment by Anju-K-M** [comment]
Hello sir,
 I had some problem in step 2,

To compile ONOS

by using this command:
echo "export ONOS_ROOT=~/onos" >> ~/.bashrc && source ~/.bashrc && source $ONOS_ROOT/tools/dev/bash_profile && cd ~/onos &&
tools/build/onos-buck build onos --show-output && tools/build/onos-buck run onos-local -- clean debug

it showed 
 IOError: [Errno 28] No space left on device.

what i do for increasing space?

**Comment by Superspider** [comment]
Do you have any offline documents?

**Comment by Anju-K-M** [comment]
> Do you have any offline documents?

No, i just follow the above online link instructions

**Comment by Superspider** [comment]
I'm very interested in your work. Now I'm studying your code. In your document, I have two files that can't be downloaded. They are _sdn-wise_java.tar.gz_ and _01-GetStarted.tar.gz._ Can you give me one? Or can anyone offer me a copy? Thank you very much.

**Comment by SebMilardo** [comment]
Please read #14

**Comment by SebMilardo** [comment]
https://github.com/sdnwiselab/sdn-wise-contiki/issues/14#issuecomment-450313432

New website url: https://sdnwiselab.github.io/

Dear all,

I have finally uploaded a backup of our website to github pages. Please let me know if everything works.

**Comment by samridhi-chawla** [comment]
Thank you so much :)

**Comment by Anju-K-M** [comment]
Hello sir,
Thank you for your information.
New website URL: https://sdnwiselab.github.io/ is very helpful for my project work. 
implementing Sdn-wise framework in the first time make some problems in installation and compile phase. 
finally, I solved that problems and the codes working correctly. 
Thank you.

**Comment by Oharaddzi** [comment]
Thanks very much for the authors. I found the website working properly and is acceptable. 

Good luck everyone!
