### ISSUE TITLE
installation error in SDNWISE

### ISSUE THREAD

**Issue by Anju-K-M** [sdnwiselab/sdn-wise-contiki#11]
Hello sir,
 I had some problem in step 2,

To compile ONOS

by using this command:
echo "export ONOS_ROOT=~/onos" >> ~/.bashrc && source ~/.bashrc && source $ONOS_ROOT/tools/dev/bash_profile && cd ~/onos &&
tools/build/onos-buck build onos --show-output && tools/build/onos-buck run onos-local -- clean debug

it showed 
 IOError: [Errno 28] No space left on device.

what i do for increasing space?? .

**Comment by SebMilardo** [comment]
https://www.howtogeek.com/124622/how-to-enlarge-a-virtual-machines-disk-in-virtualbox-or-vmware/
