### ISSUE TITLE
app not found while connecting onos in sdn wise

### ISSUE THREAD

**Issue by MiheerKulkarni** [sdnwiselab/sdn-wise-contiki#17]
Hi,
I am masters student and working on integrating onos controller with sdn-wise sink node. I have followed steps mentioned in tutorial(http://sdn-wise.dieei.unict.it/docs/guides/GetStartedONOS.html) but when I am trying to run command to activate sdnwise app in onos terminal. It gives error saying 'application not found'. Can you please help me with this ?or do I need to create one such application on onos?

**Comment by georgefatsis** [comment]
Do you mean that you try to run in the onos shell this: **app activate org.onosproject.sdnwise** and you get an error that the application is not found? 

If you mean that, before you type: **app activate org.onosproject.sdnwise** in the shell  do you see the Onos logo?

**Comment by MiheerKulkarni** [comment]
OMG!! Finally someone saw this after a year. I will just tell you what I did to solve this. Actually, ONOS migrated to Bazel build in 2018 and this tutorial is designed in 2015/16 where ONOS was build using Buck. ONOS has stopped support Buck. 
So, you have to re-design this SDN-WISE application using Bazel configuration.
Compile and run the whole stuff you will get .oar file. 
Install that file and SDN-WISE ONOS application will get installed on your machine.
I did this whole thing on Linux Ubuntu OS instead of Instant Contiki.
SO, all in all the tutorial of SDN-WISE is correct only thing is that ONOS has stopped it's support for BUCK,

**Comment by deltondmello** [comment]
Hi @MiheerKulkarni  I am having a similar issue, do you have the instructions that you used to re design SDN-WISE for onos
