### ISSUE TITLE
Refresh neighbour table

### ISSUE THREAD

**Issue by slavicat** [sdnwiselab/sdn-wise-contiki#4]
Hi,

I have noticed the following problem. When I disconnect some sensor node form the network, a sink node keeps that node in the neighbor list (within report packet) infinitely. From my point of view, it seems that neighbor table entries do not have some expiration timeout. Am I right?

**Comment by SebMilardo** [comment]
Hi!

Thanks! It's a bug, actually at the end of fill_payload_with_neighbors there should be a purge_neighbor_table(); I'm fixing it
