### ISSUE TITLE
connecting SDN-WISE to Floodlight controller

### ISSUE THREAD

**Issue by zahra7315** [sdnwiselab/sdn-wise-contiki#5]
Hello.

Is it possible to connect SDN-WISE to Floodlight controller? If so, would you please prepare a tutorial for this?

**Comment by SebMilardo** [comment]
Hi,

Is it possible? Yes it is. 
It has been done? No it hasn't 
If you want to start it as a side project, feel free. 
I'm not working full time on this project but I can help you a little bit if you start working on it

**Comment by zahra7315** [comment]
Thank you. Would you please tell me what specifically steps have you done to configure and connect to ONOS controller?

**Comment by SebMilardo** [comment]
You can refer to this commit to have an idea of all the code that has been added to onos: https://github.com/sdnwiselab/onos/commit/f4101400c06ed069010f88d1a3f05d48cfd5f797

**Comment by zahra7315** [comment]
Thanks, by the way i wanted to know if we do the same thing for the floodlight controller, should sdnwise team implement the code (in order to make floodlight work with sdnwise) ?

**Comment by SebMilardo** [comment]
Hi,

you are talking right now with all the sdnwise team, which is just me at the moment. So the answer is no, I can just help from time to time.
